// Copie MECANIQUE de KAA_PZL_kaa.json (voir ce fichier, la source de
// verite — jamais modifie a la main non plus, voir CLAUDE.md,
// 'Compatibilite des fichiers') sous forme de script classique.
//
// Meme raison d'etre que donnees/kaa-variantes.js : un fetch() ne
// fonctionne pas sur une page ouverte par double-clic (file://). Voir ce
// fichier pour l'explication complete.
//
// NE JAMAIS MODIFIER CE FICHIER A LA MAIN : re-generer a partir de
// donnees/KAA_PZL_kaa.json si son contenu change un jour.
const KAA_PZL_KAA = {
  "content": [
    {
      "PZL_name": "Mini_PZL_E_0001, (-5-5)xtr2x",
      "date": "",
      "pos": "5f4g5h5_5b1h4i6",
      "creator": "©saab",
      "type": "Mini_PZL_E",
      "winner": "Noir",
      "nb tour": "2",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_PZL_E_0002, (-5-5)xtr2x",
      "date": "",
      "pos": "5g56h7_5b1i56",
      "creator": "©saab",
      "type": "Mini_PZL_E",
      "winner": "Noir",
      "nb tour": "2",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_PZL_E_0003, (-5-5)xtr2x",
      "date": "",
      "pos": "5g5h57_5b1i68",
      "creator": "©saab",
      "type": "Mini_PZL_E",
      "winner": "Noir",
      "nb tour": "2",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_PZL_E_0004, (-5-5)xtr2x",
      "date": "",
      "pos": "5h8i78_5b1h459",
      "creator": "©saab",
      "type": "Mini_PZL_E",
      "winner": "Noir",
      "nb tour": "2",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_PZL_E_0005, (-5-5)xtr2x",
      "date": "",
      "pos": "5f56g5_5b1g3489",
      "creator": "©saab",
      "type": "Mini_PZL_E",
      "winner": "Noir",
      "nb tour": "2",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_PZL_E_0006, (-5-5)xtr2x",
      "date": "",
      "pos": "5f7g6h67_5b1i7",
      "creator": "©saab",
      "type": "Mini_PZL_E",
      "winner": "Noir",
      "nb tour": "2",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_PZL_E_0007, (-5-5)xtr2x",
      "date": "",
      "pos": "5f7g67h8_5b1h7i8",
      "creator": "©saab",
      "type": "Mini_PZL_E",
      "winner": "Noir",
      "nb tour": "2",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_PZL_E_0008, (-5-5)xtr2x",
      "date": "",
      "pos": "5f3g45h6_5b1i6",
      "creator": "©saab",
      "type": "Mini_PZL_E",
      "winner": "Noir",
      "nb tour": "2",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_PZL_E_0009, (-5-5)xtr2x",
      "date": "",
      "pos": "5g5h456_5b1i6",
      "creator": "©saab",
      "type": "Mini_PZL_E",
      "winner": "Noir",
      "nb tour": "2",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_PZL_E_0010, (-5-5)xtr2x",
      "date": "",
      "pos": "5h67i8_5b1i59",
      "creator": "©saab",
      "type": "Mini_PZL_E",
      "winner": "Noir",
      "nb tour": "2",
      "move1 sol ": "1",
      "original_type": "pzl",
      "sol": "",
      "sol_starts": "1.h7i6 2.i6i9"
    },
    {
      "PZL_name": "Mini_PZL_E_0011, (-5-5)xtr2x",
      "date": "",
      "pos": "5f5g5h78_5b1h45i6",
      "creator": "©saab",
      "type": "Mini_PZL_E",
      "winner": "Noir",
      "nb tour": "2",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_PZL_E_0012, (-5-5)xtr2x",
      "date": "",
      "pos": "5e6f7g7h7_5b1h6i68",
      "creator": "©saab",
      "type": "Mini_PZL_E",
      "winner": "Noir",
      "nb tour": "2",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_PZL_E_0013, (-5-5)xtr2x",
      "date": "",
      "pos": "5g56h57_5b1i6",
      "creator": "©saab",
      "type": "Mini_PZL_E",
      "winner": "Noir",
      "nb tour": "2",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_PZL_E_0014, (-5-5)xtr2x",
      "date": "",
      "pos": "5e4f5g5h6_5b1h7i68",
      "creator": "©saab",
      "type": "Mini_PZL_E",
      "winner": "Noir",
      "nb tour": "2",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_PZL_E_0015, (-5-5)xtr2x",
      "date": "",
      "pos": "5f3g458h7i59_5b1h49i68",
      "creator": "©saab",
      "type": "Mini_PZL_E",
      "winner": "Noir",
      "nb tour": "2",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_E_0016, (-5-5)xtr2x1",
      "date": "",
      "pos": "5g3h456i7_5b1e1f2i89",
      "creator": "©saab",
      "type": "Mini_PZL_E",
      "winner": "Noir",
      "nb tour": "2",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_E_0017, (-5-5)xtr2x1",
      "date": "",
      "pos": "5e46f6g56_5b1h57i58",
      "creator": "©saab",
      "type": "Mini_PZL_E",
      "winner": "Noir",
      "nb tour": "2",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_E_0018, (-5-5)xtr2x1",
      "date": "",
      "pos": "5c5d6f5678g5_5a3b14h5i5",
      "creator": "©saab",
      "type": "Mini_PZL_E",
      "winner": "Noir",
      "nb tour": "2",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_E_0019, (-5-5)xtr2x1",
      "date": "",
      "pos": "5d4e467f4g67_5b1e89g89",
      "creator": "©saab",
      "type": "Mini_PZL_E",
      "winner": "Noir",
      "nb tour": "2",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0001, (-5-5)xtr3x1",
      "date": "",
      "pos": "5f67g6h7_5b1i7",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0002, (-5-5)xtr3x1",
      "date": "",
      "pos": "5g67h5_5b1i56",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0003, (-5-5)xtr3x1",
      "date": "",
      "pos": "5h67i7_5b1h8i89",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0004, (-5-5)xtr4x1",
      "date": "",
      "pos": "5e8f8g8_5b1g9h9i8",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "4",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0005, (-5-5)xtr3x1",
      "date": "",
      "pos": "5g6h67i7_5b1h8i9",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0006, (-5-5)xtr3x1",
      "date": "",
      "pos": "5h56i6_5b1h89i5",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0007, (-5-5)xtr4y1",
      "date": "",
      "pos": "5b1g8h8i8_5e8f678g56h67",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Blanc",
      "nb tour": "4",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0008, (-5-5)xtr3x1",
      "date": "",
      "pos": "5f3g4h5_5b1g3h4",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0009, (-5-5)xtr3y1",
      "date": "",
      "pos": "5b1h78i7_5f7g57h56",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Blanc",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0010, (-5-5)xtr4x1",
      "date": "",
      "pos": "5e2f3g4_5b1f2h4i5",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "4",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0011, (-5-5)xtr3x1",
      "date": "",
      "pos": "5e6f7g67h68_5b1h7i7",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0012, (-5-5)xtr3x1",
      "date": "",
      "pos": "5f345h6_5b1f67h78i6",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0013, (-5-5)xtr4y1",
      "date": "",
      "pos": "5b1g57i69_5e5f678g8h67i8",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Blanc",
      "nb tour": "4",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0014, (-5-5)xtr3x1",
      "date": "",
      "pos": "5h68i7_5b1f4g5h45i59",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0015, (-5-5)xtr3x1",
      "date": "",
      "pos": "5g6h567_5b1g5h8i5",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0016, (-5-5)xtr4x1",
      "date": "",
      "pos": "5d6e7f7g8h8_5b1e8f8g9",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "4",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0017, (-5-5)xtr3x1",
      "date": "",
      "pos": "5h567_5b1i56",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0018, (-5-5)xtr3x1",
      "date": "",
      "pos": "5e5f6g6h67i8_5b1f5g578i7",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0019, (-5-5)xtr4x1",
      "date": "",
      "pos": "5e6f578g6h67i8_5b1g578h5",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "4",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0020, (-5-5)xtr3y1",
      "date": "",
      "pos": "5b1h58i589_5f5g5h67i67",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Blanc",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0021, (-5-5)xtr3x1",
      "date": "",
      "pos": "5e3f46g6h78_5b1g57h5i7",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0022, (-5-5)xtr3x1",
      "date": "",
      "pos": "5e57f68g8h67i8_5b1g57h8i6",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0023, (-5-5)xtr4x1",
      "date": "",
      "pos": "5e3f46g6h7_5b1g5h5i7",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "4",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0024, (-5-5)xtr3y1",
      "date": "",
      "pos": "5b1e1f2g34h4i56_5h567",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Blanc",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0025, (-5-5)xtr3x1",
      "date": "",
      "pos": "5e5f6g6h67i9_5b1g578h5i7",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0026, (-5-5)xtr4x1",
      "date": "",
      "pos": "5e5f456g6h67_5b1e46g57h58i7",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "4",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0027, (-5-5)xtr3x1",
      "date": "",
      "pos": "5h57i6_5b1h89i5",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0028, (-5-5)xtr3y1",
      "date": "",
      "pos": "5b1g8h89i8_5e8f678g67",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Blanc",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0029, (-5-5)xtr4x1",
      "date": "",
      "pos": "5e45f34g6h67i6_5b1g457h8",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "4",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0030, (-5-5)xtr3x1",
      "date": "",
      "pos": "5e45f6g6h67_5b1g57h58i7",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0031, (-5-5)xtr3x1",
      "date": "",
      "pos": "5e6f56g67h7_5b1f34g45h5i56",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Noir",
      "nb tour": "3",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Mini_Pzl_M_0032, (-5-5)xtr4y1",
      "date": "",
      "pos": "5b1d6e46f56g5i7_5g7h678i6",
      "creator": "©saab",
      "type": "Mini_PZL_M",
      "winner": "Blanc",
      "nb tour": "4",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0001, (-5-4)xtr2y1",
      "date": "",
      "pos": "5a1b126c24d13e3_4a234b5c135d24e4",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Blanc",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0002, (-5-5)xtr2x1",
      "date": "",
      "pos": "5e4f56g36h45i67_5e123f2g47h6i89",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0003, (-5-5)xtr2x1",
      "date": "",
      "pos": "5b4c4d468e3478_5e126f4789g49",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0004, (-5-5)xtr2x1",
      "date": "",
      "pos": "5c23e45f3456g4_5a3b13d4e23g356",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0005, (-5-5)xtr2x1",
      "date": "",
      "pos": "5a2b1c234d47e37_5a135b345c6d8e9",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0006, (-5-5)xtr2x1",
      "date": "",
      "pos": "5b34d346e13f34_5a24b25c235d12",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0007, (-5-5)xtr2x1",
      "date": "",
      "pos": "5c2d4e245f6g56i5_5b12c34e1f34g4h4",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0008, (-5-5)xtr2x1",
      "date": "",
      "pos": "5c34d345f46g57_5b1d2e2f5h68i679",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0009, (-5-5)xtr2x1",
      "date": "",
      "pos": "5a5b5c34d56e57f7_5a1b236c56d78e8",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0010, (-5-5)xtr2x1",
      "date": "",
      "pos": "5a5b24c45d246e4_5b56c26d15e56f5",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0011, (-5-5)xtr2x1",
      "date": "",
      "pos": "5a12b123c5d68e8_5a45b45c4e7f89g9",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0012, (-5-5)xtr2x1",
      "date": "",
      "pos": "5a12b2c457d46e5_5a45b1456c6d78",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0013, (-5-5)xtr2x1",
      "date": "",
      "pos": "5c5d6e34f567g46_5a3b46c6e12f34g3",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0014, (-5-5)xtr2x1",
      "date": "",
      "pos": "5a2b345c4d4e45f6_5a13c123d3e123",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0015, (-5-5)xtr2x1",
      "date": "",
      "pos": "5f467g356h8i78_5f23g4h4569i56",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0016, (-5-5)xtr2x1",
      "date": "",
      "pos": "5a1c34d4e346f47_5b1d2e5f56g48h49",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0017, (-5-5)xtr2x1",
      "date": "",
      "pos": "5d3e4789f567g7_5c3d4678e56h7i8",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0018, (-5-5)xtr2x1",
      "date": "",
      "pos": "5c35d46e4679f7_5a15b2356c4d78",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0019, (-5-5)xtr2x1",
      "date": "",
      "pos": "5c6d346e679f8g8_5c7d12e58f679h8",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0020, (-5-5)xtr2x1",
      "date": "",
      "pos": "5a5b3c45d6e36f46_5a3b25c2367d23",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0021, (-5-5)xtr2x1",
      "date": "",
      "pos": "5a34b5c7d36e13f4_5a12b126c36d12",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0022, (-5-5)xtr2x1",
      "date": "",
      "pos": "5e56f5678g6h8i9_5d678e89g789h7",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0023, (-5-5)xtr2x1",
      "date": "",
      "pos": "5d3e35f45g67i56_5f23g45h478i79",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0024, (-5-5)xtr2x1",
      "date": "",
      "pos": "5e34f35g467h5i9_5b2c12d3f2g8h78i7",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0025, (-5-5)xtr2x1",
      "date": "",
      "pos": "5c45d35e36f56g7_5e4f347g38h89i9",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0026, (-5-5)xtr2x1",
      "date": "",
      "pos": "5a345c234d5e6g7_5a1b26c56f7g8h8i9",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0027, (-5-5)xtr2x1",
      "date": "",
      "pos": "5b23c4d56e789f7_5a1b56c256d278",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0028, (-5-5)xtr2x1",
      "date": "",
      "pos": "5b5c5d6e6f8h567i9_5b6c7d7e8f9g89h8i8",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0029, (-5-5)xtr2x1",
      "date": "",
      "pos": "5a1b5c3d34567e5_5a2b346c12d2e8f9",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0030, (-5-5)xtr2x1",
      "date": "",
      "pos": "5b4d5e45f5g67h8i9_5a4b56c56h67i67",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0031, (-5-5)xtr2x1",
      "date": "",
      "pos": "5a23b2c123def4_5a45c45d125e12",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_E_0032, (-5-5)xtr2x1",
      "date": "",
      "pos": "5d58e68f489g59_5f7g7h678i5689",
      "creator": "©saab",
      "type": "PZL_E",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0001, (-3-5)xtr3x1",
      "date": "",
      "pos": "3b4c4d567e5f4567g6_4a3b23d234e346",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0002, (-5-5)xtr3x1",
      "date": "",
      "pos": "5c4d456e45f56g6_5a12b2c123d23e3",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0003, (-5-5)xtr3x1",
      "date": "",
      "pos": "5e18f9g568h5i56_5e279f7g34h8i89",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0004, (-3-5)xtr3x1",
      "date": "",
      "pos": "3b4c3d567e5f4567g6_5a4b23d234e346",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0005, (-5-5)xtr3x1",
      "date": "",
      "pos": "5b5c6d56e56f7g78_5b4c57e78f6h78i7",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0006, (-5-5)xtr3x1",
      "date": "",
      "pos": "5a2b234d134e35_5a14b5c35e2f34g3",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0007, (-5-5)xtr3x1",
      "date": "",
      "pos": "5b2c12d456e35f2_5d137e12f3g34h5",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0008, (-5-5)xtr3x1",
      "date": "",
      "pos": "5c13d23e45f34g4_5b23c2d4e23g35h5",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0009, (-5-5)xtr3x1",
      "date": "",
      "pos": "5c6e34f236g346_5d12e6f8g7h458i5",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Blanc",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0010, (-5-5)xtr4x1",
      "date": "",
      "pos": "5a3b35d1e12f4g5i5_5a15b12c3d3f3h45",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0011, (-5-5)xtr3y1",
      "date": "",
      "pos": "5a45b56c6e1f2g4h5_5b23c45d567e8h4",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Blanc",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0012, (-5-5)xtr3y1",
      "date": "",
      "pos": "5d4e5f345g478i8_5e23f68g35h589",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Blanc",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0013, (-5-5)xtr3x1",
      "date": "",
      "pos": "5e56f678g58h7i7_5e78g3479h68",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl",
      "sol": "",
      "sol_starts": "1.f8h8 2.g8i8 3.h7h9"
    },
    {
      "PZL_name": "Pzl_M_0014, (-5-5)xtr3y1",
      "date": "",
      "pos": "5d12e6f8g7h458i5_5c6e34f346g346",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Blanc",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0015, (-3-5)xtr4x1",
      "date": "",
      "pos": "3c24d356e2346f47_5d4f356g3467h7",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0016, (-5-5)xtr4x1",
      "date": "",
      "pos": "5b34c4d5678e57_5a3b25c35e68f89",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Noir",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0017, (-4-4)xtr4y1",
      "date": "",
      "pos": "4a12b15c56e78f6g8_4a35b23c34d46e6h6",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Blanc",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0018, (-5-3)xtr4y1",
      "date": "",
      "pos": "5d4f2356g467h7_3c24d356e2346f47",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Blanc",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0019, (-4-4)xtr4y1",
      "date": "",
      "pos": "4a45b56c67e3f4h56_4b34c45d4567e78",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Blanc",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0020, (-5-5)xtr4y1",
      "date": "",
      "pos": "5e23f6g3589h68_5e45f345g467h7",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Blanc",
      "nb tour": "",
      "move1 sol ": "1",
      "original_type": "pzl"
    },
    {
      "PZL_name": "Pzl_M_0021, (-4-4)xtr4x1",
      "date": "",
      "pos": "4b5c6d56e567f68h6_4a3b2346c3457d7",
      "creator": "©saab",
      "type": "PZL_M",
      "winner": "Noir",
      "nb tour": "4",
      "move1 sol ": "1",
      "original_type": "pzl",
      "sol": "",
      "sol_starts": "d5d7 b6e9 d6d8 b2b5 b6d6 | d5d7 b6e9 d6d8 c7b6 f8e8"
    }
  ]
};
